version: 2.1

# Orb for using Git commands
orbs:
  git: circleci/git@2.2.0

jobs:
  update_jira_tickets:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - git/clone
      - run:
          name: Extract Jira Issue Codes
          command: |
            chmod +x .circleci/extract_jira_issues.sh
            TAG_NAME=${CIRCLE_TAG}
            if [ -z "$TAG_NAME" ]; then
              echo "This job only runs on tag pushes. Exiting."
              exit 1
            fi
            .circleci/extract_jira_issues.sh $TAG_NAME

workflows:
  version: 2
  build_and_update_jira:
    jobs:
      - update_jira_tickets:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
