name: Update Jira Tickets on Tag Release

on:
  push:
    tags:
      - '*'

jobs:
  update-jira-tickets:
    runs-on: ubuntu-latest
    env:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Jira Issue Codes and Update Issues
        run: .github/scripts/extract_jira_issues.sh

