name: Update Jira Tickets on Tag Release

on:
  push:
    tags:
      - '*'
jobs:
  update-jira-tickets:
    runs-on: ubuntu-latest
    env:
      JIRA_WEBHOOK_IP: ${{ secrets.JIRA_WEBHOOK_IP }}
      JIRA_WEBHOOK_JTD: ${{ secrets.JIRA_WEBHOOK_JTD }}
      JIRA_WEBHOOK_LDST: ${{ secrets.JIRA_WEBHOOK_LDST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Jira Issue Codes and Update Issues
        run: .github/scripts/extract_jira_issues.sh

